title: "Konkani Recipes"
comment: "Authentic Konkani Dishes from Coastal Karnataka"
permalink: /:title.html
paginate: 8
auto:        false
lsi:         false
highlighter: 'rouge'
markdown:    kramdown
plugins: [jekyll-paginate]
exclude:
  - README.md
