title: "Konkani Recipes"
comment: "Authentic Konkani Dishes from Coastal Karnataka"
permalink: /:title
paginate: 5
auto:        false
lsi:         false
pygments:    true
markdown:    kramdown
exclude:
  - README.md
