# This sets a blank configuation. See:
#
# https://github.com/mojombo/jekyll/wiki/configuration
#
# For more details about configuring Jekyll.
#
title: "Konkani Recipes"
permalink: /:title
exclude:
  - README.md
paginate: 5