title: "Konkani Recipes"
comment: "Authentic Konkani Dishes from Coastal Karnataka"
permalink: /:title.html
paginate: 8
auto:        false
lsi:         false
pygments:    true
markdown:    kramdown
exclude:
  - README.md
